spring.application.name=PetShop
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QL_PetShop;encrypt=true;trustServerCertificate=true;sendTimeAsDatetime=false;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.web.resources.static-locations=classpath:/static/,file:src/main/webapp/
spring.web.resources.add-mappings=true

server.port=8080
server.servlet.context-path=/
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl